-- Melhor time estatisticamente de 2017
USE NBA;
SELECT GAMES.SEASON, TEAMS.NAME, (AVG(GAMES.PTS_HOME) + AVG(GAMES.AST_HOME) + AVG(GAMES.REB_HOME) + AVG(GAMES.PTS_AWAY) + AVG(GAMES.AST_AWAY) + AVG(GAMES.REB_AWAY)) AS PONTUAÇÃO
FROM GAMES INNER JOIN TEAMS ON GAMES.HOME_TEAM_ID = TEAMS.TEAM_ID
WHERE GAMES.SEASON = '2017'
GROUP BY GAMES.HOME_TEAM_ID
ORDER BY PONTUAÇÃO DESC
LIMIT 10;